trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install pandas numpy pyspark requests pymongo mysql-connector-python papermill -q
  displayName: 'Install Dependencies'

- script: |
    papermill CustomerOrder_Pipeline.ipynb CustomerOrder_Pipeline_Output.ipynb
  displayName: 'Run CustomerOrder_Pipeline Notebook'

- script: |
    echo "Pipeline executed successfully"
  displayName: 'Success Message'
